export const JOB_CATEGORIES = [
  {
    category: "General Admin",
    roles: [
      "Virtual Assistant",
      "Executive Assistant",
      "Data Entry Specialist",
      "Project Manager",
      "Personal Assistant",
      "Recruitment Assistant",
      "Researcher",
      "Appointment Setter",
      "HR Assistant",
    ],
    exampleTasks: "Managing emails and calendars, Scheduling meetings, Filing and organizing data",
  },
  {
    category: "Marketing & Sales",
    roles: [
      "Social Media Marketing",
      "SEO",
      "Sales Representative",
      "Lead Generation Specialist",
      "Facebook & Meta Ads Specialist",
      "Google Ads/PPC Expert",
      "Email Marketing Specialist",
      "Affiliate Marketing",
      "Instagram Marketing",
      "CRM / Funnels Specialist",
    ],
    exampleTasks: "Create and manage ad campaigns, Grow social accounts, Manage email funnels, Research new leads for sales",
  },
  {
    category: "Software & Development",
    roles: [
      "Web Developer",
      "Mobile App Developer",
      "PHP/Python/JavaScript Developer",
      "Laravel/Ruby on Rails Developer",
      "Shopify Developer",
      "Full-stack Developer",
      "App & Software Programmer",
    ],
    exampleTasks: "Build websites and apps, Integrate APIs, Maintain existing systems",
  },
  {
    category: "Creative & Multimedia",
    roles: [
      "Graphic Designer",
      "Video Editor/Animator",
      "Content Creator",
      "Photoshop/Illustrator Expert",
      "Multimedia Designer",
      "Short-form Video Editor",
      "Sales Funnel Creative Designer",
    ],
    exampleTasks: "Editing reels and YouTube videos, Designing promotional graphics, Creating brand visuals",
  },
  {
    category: "Customer Service & Support",
    roles: [
      "Customer Support",
      "Chat Sales Agent",
      "Support Representative",
      "Tech Support Specialist",
      "Client Relationship Support",
    ],
    exampleTasks: "Responding to customer questions, Troubleshooting issues, Live chat support",
  },
  {
    category: "Writing & Content",
    roles: [
      "Content Writer",
      "SEO Writer",
      "Copywriter",
      "Transcriptionist",
      "Blog/Email Writer",
    ],
    exampleTasks: "Write articles and blog posts, Help with newsletters, Transcribe audio files",
  },
  {
    category: "E-Commerce & Marketplace Support",
    roles: [
      "Amazon E-Commerce Specialist",
      "Shopify Manager",
      "Product Listing Specialist",
      "Google Shopping Specialist",
      "Sales Funnel Builder",
    ],
    exampleTasks: "Optimize product listings, Run marketplace ads, Build sales funnels",
  },
  {
    category: "Finance & Accounting",
    roles: [
      "Accountant/Bookkeeper",
      "Financial Analyst",
      "Accounts Assistant",
      "Tax Preparation / MYOB Specialist",
    ],
    exampleTasks: "Managing accounts, Preparing financial reports, Handling tax documentation",
  },
];
